### ISSUE TITLE
Add support for conditional requests with ETag and Last-Modified headers

### ISSUE THREAD

**Issue by JWCook** [requests-cache/aiohttp-client-cache#79] opened 2021-08-14 14:54 UTC
Quick summary of how this would work:
* If a cached response contains an `ETag` header, add an `If-None-Match` header to the new request
* If a cached response contains a `Last-Modified` header, add an `If-Modified-Since` header to the new request
* If a `304 Not Modified` response is received, return the cached response and update expiration and headers (if changed)
* If a `200` response is received, update the cache and return the new response

**Comment by netomi** [comment] 2023-10-01 21:53
I have a workaround implemented which can be found here:

https://github.com/netomi/otterdog/blob/main/otterdog/providers/github/rest/requester.py#L182

I am willing to work on a patch to have this integrated in this library by default.

Something that I noticed while working on the workaround: when using session.disabled() to temporarily disable the cache, this is only valid for getting requests from the cache, the cache itself is still updated with responses received from the remote server, this should be fixed imho, as it is misleading, will create a separate ticket for it.

**Comment by JWCook** [comment] 2023-10-02 01:33
> I am willing to work on a patch to have this integrated in this library by default.

That would be great! Thank you.

> when using session.disabled()... the cache itself is still updated with responses

That's not the intended behavior, and this is supposed to be handled [here](https://github.com/requests-cache/aiohttp-client-cache/blob/main/aiohttp_client_cache/backends/base.py#L92). Thanks for the heads up.

**Comment by netomi** [comment] 2023-10-02 07:53
Created #182 to illustrate the problem. The problem is that there are 2 ways to determine whether the cache is used. Via the cache actions and the is_cacheable method which leads to very wrong behavior when the cache is disabled which is hidden from the user. I just noticed some problems as strangely some cached responses got removed and I wanted to understand why.

**Closed** 2023-10-27 16:51 UTC
Labels: enhancement
