### ISSUE TITLE
aiohttp 3.10.6+ compatibility

### ISSUE THREAD

**Issue by seriaati** [requests-cache/aiohttp-client-cache#251] opened 2024-09-25 07:49 UTC
### The problem

```
  File "c:\Users\seria\source\repos\main\akasha-py\akasha\client.py", line 266, in get_categories
    data = await self._request(
           ^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\seria\source\repos\main\akasha-py\akasha\client.py", line 96, in _request
    async with self._session.get(url, params=params) as response:
  File "C:\Users\seria\source\repos\main\akasha-py\.venv\Lib\site-packages\aiohttp\client.py", line 1364, in __aexit__
    await self._resp.__aexit__(exc_type, exc, tb)
          ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'CachedResponse' object has no attribute '__aexit__'. Did you mean: '__init__'?
```

### Expected behavior

No error.

### Steps to reproduce the behavior

```py
import asyncio
from aiohttp_client_cache.backends.sqlite import SQLiteBackend
from aiohttp_client_cache.session import CachedSession


async def main():
    cache = SQLiteBackend()
    async with CachedSession(cache=cache) as session:
        async with session.get("https://httpbin.org/get") as response:
            print(await response.text())


asyncio.run(main())
```

Run this twice, the result:
```ps
PS C:\Users\seria\source\repos\main\akasha-py> & c:/Users/seria/source/repos/main/akasha-py/.venv/Scripts/python.exe c:/Users/seria/source/repos/main/akasha-py/test.py
{
  "args": {},
  "headers": {
    "Accept": "*/*",
    "Accept-Encoding": "gzip, deflate",
    "Host": "httpbin.org",
    "User-Agent": "Python/3.11 aiohttp/3.10.6",
    "X-Amzn-Trace-Id": "Root=1-66f3c006-32f11c4e4b59ed5c6789f7c7"
  },
  "origin": "124.218.93.178",
  "url": "https://httpbin.org/get"
}

PS C:\Users\seria\source\repos\main\akasha-py> & c:/Users/seria/source/repos/main/akasha-py/.venv/Scripts/python.exe c:/Users/seria/source/repos/main/akasha-py/test.py
{
  "args": {},
  "headers": {
    "Accept": "*/*",
    "Accept-Encoding": "gzip, deflate",
    "Host": "httpbin.org",
    "User-Agent": "Python/3.11 aiohttp/3.10.6",
    "X-Amzn-Trace-Id": "Root=1-66f3c006-32f11c4e4b59ed5c6789f7c7"
  },
  "origin": "124.218.93.178",
  "url": "https://httpbin.org/get"
}

Traceback (most recent call last):
  File "c:\Users\seria\source\repos\main\akasha-py\test.py", line 13, in <module>
    asyncio.run(main())
  File "C:\Users\seria\AppData\Roaming\uv\python\cpython-3.11.9-windows-x86_64-none\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\seria\AppData\Roaming\uv\python\cpython-3.11.9-windows-x86_64-none\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\seria\AppData\Roaming\uv\python\cpython-3.11.9-windows-x86_64-none\Lib\asyncio\base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "c:\Users\seria\source\repos\main\akasha-py\test.py", line 9, in main
    async with session.get("https://httpbin.org/get") as response:
  File "C:\Users\seria\source\repos\main\akasha-py\.venv\Lib\site-packages\aiohttp\client.py", line 1364, in __aexit__
    await self._resp.__aexit__(exc_type, exc, tb)
          ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'CachedResponse' object has no attribute '__aexit__'. Did you mean: '__init__'?
```

### Workarounds

Downgrade aiohttp from `3.10.6` to `3.10.5`

### Environment

- aiohttp-client-cache version: `0.1.11`
- Python version: `3.11`
- Platform: Windows 11

**Comment by alessio-locatelli** [comment] 2024-09-25 09:41
@JWCook Perhaps there was a reason for `CachedResponse` **not**  to  inherit from `ClientResponse`. It is correct that you want to keep adding/updating methods to the `CachedResponse` to stay compatible? 

@JWCook @seriaati I can investigate a possible fix (perhaps just adding `__aenter__`), but please let me know if you going to submit a PR.

**Comment by seriaati** [comment] 2024-09-25 10:18
@alessio-locatelli Nope, I'm not working on a fix for it right now.

**Comment by JWCook** [comment] 2024-09-25 15:46
Thanks for the bug report!

@alessio-locatelli I think my reason for not subclassing `ClientResponse` was to create a slotted class for a minor performance improvement in the case of very high request rates. Compatibility is more important, though, so I would be fine with changing that to subclass `ClientResponse`.

If you have time to make that change, that would be great; otherwise I can get to it this weekend. Thanks!

**Comment by alessio-locatelli** [comment] 2024-09-27 05:50
I have a "work in progress" branch https://github.com/alessio-locatelli/aiohttp-client-cache/tree/fix_interface_compatibility that updates  `CachedResponse` to inherit from the `aiohttp.Response`, but it it still in a very dirty state and is far away from a working version. This work can potentially result in less code and a cleaner interface, but it has taken much more time and effort than I expected, so I will be happy to review any small temporary fixes.

**Comment by jamesbraza** [comment] 2024-10-01 17:41
Thank you @alessio-locatelli and @JWCook. Would you mind cutting a new release for this?

**Comment by JWCook** [comment] 2024-10-01 17:43
Sure! You can expect a new release by tomorrow.

**Comment by jamesbraza** [comment] 2024-10-02 06:34
With the newly released `aiohttp-client-cache==0.12.0` and `aiohttp==3.10.8` at this line: https://github.com/aio-libs/aiohttp/blob/v3.10.8/aiohttp/client_reqrep.py#L1215

I am getting `AttributeError: 'CachedResponse' object has no attribute '_resolve_charset'`. Here's the full stack:

```none
a.py: in foo
    text = await response.text()
.venv/lib/python3.12/site-packages/aiohttp/client_reqrep.py:1223: in text
    encoding = self.get_encoding()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <ClientResponse(https://api.crossref.org/works/10.1038/nature10362/transform/application/x-bibtex) [200 OK]>
<CIMultiD...imit-limit': '150', 'x-rate-limit-interval': '1s', 'permissions-policy': 'interest-cohort=()', 'connection': 'close')>


    def get_encoding(self) -> str:
        ctype = self.headers.get(hdrs.CONTENT_TYPE, "").lower()
        mimetype = helpers.parse_mimetype(ctype)
    
        encoding = mimetype.parameters.get("charset")
        if encoding:
            with contextlib.suppress(LookupError, ValueError):
                return codecs.lookup(encoding).name
    
        if mimetype.type == "application" and (
            mimetype.subtype == "json" or mimetype.subtype == "rdap"
        ):
            # RFC 7159 states that the default encoding is UTF-8.
            # RFC 7483 defines application/rdap+json
            return "utf-8"
    
        if self._body is None:
            raise RuntimeError(
                "Cannot compute fallback encoding of a not yet read body"
            )
    
>       return self._resolve_charset(self, self._body)
E       AttributeError: 'CachedResponse' object has no attribute '_resolve_charset'
```

I think perhaps `ClientResponse .get_encoding` doesn't yet work

**Comment by alessio-locatelli** [comment] 2024-10-02 06:39
@jamesbraza I will check today, but it looks like a side effect of using the old cache. Could you please try removing the old cache?

**Comment by alessio-locatelli** [comment] 2024-10-02 07:10
@jamesbraza I see that `self._resolve_charset` is not restored during unpickling. 

`self._resolve_charset` is not picklable:
```py
E       _pickle.PicklingError: Can't pickle <function ClientSession.<lambda> at 0x7f94fdd13c40>: attribute lookup ClientSession.<lambda> on aiohttp.client failed
```
so I had to exclude it.

I will think how can I restore it correctly and I will publish a bugfix.

**Comment by JWCook** [comment] 2024-10-02 17:02
@alessio-locatelli Thanks for taking care of this!

**Comment by jamesbraza** [comment] 2024-10-02 17:11
Thank you @alessio-locatelli , nice work! I was less productive than you last night lol

**Comment by jamesbraza** [comment] 2024-10-02 18:21
@alessio-locatelli I see you recently made https://github.com/requests-cache/aiohttp-client-cache/tree/v0.12.2, but it didn't show up in PyPI. Not sure if you are aware of that or not, more just sharing

**Comment by JWCook** [comment] 2024-10-02 18:30
v0.12.2 is available on PyPI now. Give that a try and let us know if you run into any more issues.

**Comment by jamesbraza** [comment] 2024-10-02 19:45
Yep just gave it a whirl, and with `aiohttp-client-cache==0.12.2` and `aiohttp==3.10.8`:

```none
  File "/home/runner/work/repo/repo/a.py", line 1065, in foo
    data = await response.json()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/repo/repo/.venv/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1258, in json
    encoding = self.get_encoding()
               ^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/repo/repo/.venv/lib/python3.12/site-packages/aiohttp_client_cache/response.py", line 94, in get_encoding
    return self._encoding
           ^^^^^^^^^^^^^^
AttributeError: 'CachedResponse' object has no attribute '_encoding'. Did you mean: 'get_encoding'?
```

Does this mean I need to wipe my cache?

**Comment by JWCook** [comment] 2024-10-02 19:51
> Does this mean I need to wipe my cache?

That would be the first thing I'd try. I can't reproduce that locally or in tests right now, but I will take a closer look later today.

Could you share an example that reproduces this in a new virtualenv and a new cache? That would help narrow it down.

**Comment by layday** [comment] 2024-10-02 20:35
Some additional information [here](https://github.com/requests-cache/aiohttp-client-cache/pull/257#issuecomment-2389639992).

**Comment by jamesbraza** [comment] 2024-10-03 05:26
Wiping the cache did not resolve my issue. Even with `aiohttp==3.10.5` (and `aiohttp-client-cache==0.12.2`), I am still getting:

```none
    data = await response.json()
.venv/lib/python3.12/site-packages/aiohttp/client_reqrep.py:1258: in json
    encoding = self.get_encoding()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <ClientResponse(https://<redacted>', 'X-Amz-Cf-Pop': '<redacted>', 'X-Amz-Cf-Id': '<redacted>')>


    def get_encoding(self):
>       return self._encoding
E       AttributeError: 'CachedResponse' object has no attribute '_encoding'. Did you mean: 'get_encoding'?

.venv/lib/python3.12/site-packages/aiohttp_client_cache/response.py:94: AttributeError
```

**Comment by layday** [comment] 2024-10-03 07:06
Note that it's not just `_resolve_charset` that might not be picklable.  Any response with a trace config callback is also not pickleable.  There might also be other cases I'm not aware of.  Since `ClientResponse` makes no pickling guarantees, and pickling is crucial for caching, it might make more sense to revert this change.

**Comment by alessio-locatelli** [comment] 2024-10-04 07:22
@JWCook @layday I created a ["dev" branch](https://github.com/requests-cache/aiohttp-client-cache/tree/dev) where:
1. Reverted all back https://github.com/requests-cache/aiohttp-client-cache/pull/262
2. Added `__aexit__` to fix the original issue: https://github.com/requests-cache/aiohttp-client-cache/pull/263

If that is OK, @JWCook can take the changes into the "main".

**Comment by layday** [comment] 2024-10-04 08:25
I tried this branch and I'm receiving the following error with logging enabled:

```
[...]

  File "/Users/dimitris/Code/instawow/.nox/dev_env-3-12/lib/python3.12/site-packages/aiohttp/client.py", line 1357, in __aenter__
    self._resp: _RetType = await self._coro
    │    │                       │    └ <member '_coro' of '_BaseRequestContextManager' objects>
    │    │                       └ <aiohttp.client._BaseRequestContextManager object at 0x10241bfd0>
    │    └ <member '_resp' of '_BaseRequestContextManager' objects>
    └ <aiohttp.client._BaseRequestContextManager object at 0x10241bfd0>
  File "/Users/dimitris/Code/instawow/.nox/dev_env-3-12/lib/python3.12/site-packages/aiohttp_client_cache/session.py", line 90, in _request
    response = await self.cache.request(actions)
                     │    │     │       └ CacheActions(cache_control=False, expire_after=datetime.timedelta(days=1), key='5fb90f203e00ccf063bce5dd46ab83cf90b3cbdeb108b...
                     │    │     └ <function CacheBackend.request at 0x102ec5d00>
                     │    └ <aiohttp_client_cache.backends.base.CacheBackend object at 0x102edd3a0>
                     └ <aiohttp_client_cache.session.CachedSession object at 0x102ede450>
  File "/Users/dimitris/Code/instawow/.nox/dev_env-3-12/lib/python3.12/site-packages/aiohttp_client_cache/backends/base.py", line 149, in request
    response = None if actions.skip_read else await self.get_response(actions.key)
                       │       │                    │    │            │       └ <member 'key' of 'CacheActions' objects>
                       │       │                    │    │            └ CacheActions(cache_control=False, expire_after=datetime.timedelta(days=1), key='5fb90f203e00ccf063bce5dd46ab83cf90b3cbdeb108b...
                       │       │                    │    └ <function CacheBackend.get_response at 0x102ec5da0>
                       │       │                    └ <aiohttp_client_cache.backends.base.CacheBackend object at 0x102edd3a0>
                       │       └ <member 'skip_read' of 'CacheActions' objects>
                       └ CacheActions(cache_control=False, expire_after=datetime.timedelta(days=1), key='5fb90f203e00ccf063bce5dd46ab83cf90b3cbdeb108b...
  File "/Users/dimitris/Code/instawow/.nox/dev_env-3-12/lib/python3.12/site-packages/aiohttp_client_cache/backends/base.py", line 167, in get_response
    elif not await self.is_cacheable(response):  # type: ignore
                   │    │            └ <unprintable CachedResponse object>
                   │    └ <function CacheBackend.is_cacheable at 0x102ec5bc0>
                   └ <aiohttp_client_cache.backends.base.CacheBackend object at 0x102edd3a0>
  File "/Users/dimitris/Code/instawow/.nox/dev_env-3-12/lib/python3.12/site-packages/aiohttp_client_cache/backends/base.py", line 105, in is_cacheable
    logger.debug(f'Pre-cache checks for response from {response.url}: {cache_criteria}')
    │      │                                           │        │      └ {'disabled cache': False, 'disabled method': False, 'disabled status': False, 'disabled by filter': False, 'disabled by heade...
    │      │                                           │        └ <member 'url' of 'CachedResponse' objects>
    │      │                                           └ <unprintable CachedResponse object>
    │      └ <function Logger.debug at 0x101fe1620>
    └ <Logger aiohttp_client_cache.backends.base (WARNING)>

AttributeError: 'CachedResponse' object has no attribute 'url'
```

**Comment by alessio-locatelli** [comment] 2024-10-04 08:57
> AttributeError: 'CachedResponse' object has no attribute 'url'

How can it disappear? https://github.com/requests-cache/aiohttp-client-cache/blob/dev/aiohttp_client_cache/response.py#L65 @layday  How can I reproduce this? The MRE from the issue description works and the tests work too.

**Comment by layday** [comment] 2024-10-04 09:35
It appears to have been a caching issue - it's gone away after clearing the cache. I'm not sure how it got into that state and I can't replicate it now, but I assume it had something to do with switching to the dev branch w/ a hot cache and retrieving a cached response.

**Comment by JWCook** [comment] 2024-10-04 16:36
Thanks for your patience, everyone. I believe all these issues are fixed in v0.12.3. Please confirm if that's working for you.

**Comment by JWCook** [comment] 2024-10-04 16:46
As you can see, serialization is one of the trickier parts of this problem space! I reopened #67 (adding `cattrs`), which is the approach I've had the most success with over in [requests-cache](https://github.com/requests-cache/requests-cache).  The downside is we still need to keep up with any changes in `aiohttp`'s `ClientResponse` class instead of relying on inheritance, but it eliminates several other types of problem that are more difficult to debug (like some of the ones we encountered here).

**Comment by layday** [comment] 2024-10-05 13:57
No issues with v0.12.3 from my side. Thank you!

**Closed** 2024-10-05 14:06 UTC
Labels: bug

**Comment by jamesbraza** [comment] 2024-10-05 22:42
Yes it's working for me too, nice job team
